version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "master"
    allow:
      - dependency-type: "direct"
    assignees:
      - "WterBerg"
