codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    status:
        project:
            default:
                target: 80%
                threshold: 5%

    precision: 2
    round: down
    range: '80...100'
