os: linux
dist: focal
language: php
php: 7.4

addons:
  sonarcloud:
    organization: $SONARCLOUD_ORGANIZATION

git:
  depth: false
  submodules: false
  quiet: true

cache:
  directories:
    - '$HOME/.composer/cache/files'
    - '$HOME/.sonar/cache'

before_install:
  - composer self-update
  - composer global require friendsofphp/php-cs-fixer --prefer-dist --prefer-stable --no-progress --no-interaction
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - composer install --no-suggest --dev --prefer-dist --no-scripts --no-interaction

script:
  - vendor/bin/phpunit
  - php-cs-fixer fix --dry-run
  - sonar-scanner -D"sonar.host.url=$SONARCLOUD_HOST" -D"sonar.login=$SONARCLOUD_TOKEN"
