os: linux
dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4

jobs:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

git:
  depth: false
  submodules: false
  quiet: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install --no-suggest --dev --prefer-dist --no-scripts --no-interaction --quiet

script:
  - bash vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover=clover.xml
  - bash vendor/bin/php-cs-fixer fix --dry-run

after_success:
  - bash <(curl -s https://codecov.io/bash)
