os: linux
language: php

jobs:
  include:
    - php: 7.2
      dist: xenial
    - php: 7.2
      dist: bionic
    - php: 7.2
      dist: focal

    - php: 7.3
      dist: xenial
    - php: 7.3
      dist: bionic
    - php: 7.3
      dist: focal

    - php: 7.4
      dist: xenial
    - php: 7.4
      dist: bionic
    - php: 7.4
      dist: focal

addons:
  sonarcloud:
    organization: "github-wterberg"
    token:
      secure: $SONARCLOUD_TOKEN

git:
  depth: false
  submodules: false
  quiet: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - composer global require friendsofphp/php-cs-fixer --prefer-dist --prefer-stable --no-progress --no-interaction --quiet
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - composer install --no-suggest --dev --prefer-dist --no-scripts --no-interaction --quiet

script:
  - vendor/bin/phpunit
  - php-cs-fixer fix --dry-run
  - sonar-scanner -Dsonar.sources=src -Dsonar.sourceEncoding=UTF-8 -Dsonar.php.tests.reportPath=./test-reports/phpunit/junit.xml -Dsonar.php.coverage.reportPaths=./test-reports/phpunit/coverage.xml -Dsonar.working.directory=./test-reports/sonar-scanner
